server:
  port: 8080

spring:
  application:
    name: hadoop-movie-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 根据你的虚拟机或本机 MySQL 地址修改连接信息。
    url: jdbc:mysql://139.155.136.111:13306/movie_analytics?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  configuration:
    # 下划线字段自动映射到 Java 驼峰属性，例如 release_year -> releaseYear。
    map-underscore-to-camel-case: true
  global-config:
    banner: false

movie:
  hadoop:
    # 根据你的虚拟机 Hadoop 集群地址修改 NameNode URI。
    hdfs-uri: hdfs://139.155.136.111:9001
    # 原始影视数据目录。
    raw-data-path: /movie/raw
    # 清洗后影视数据目录。
    clean-data-path: /movie/clean
    # Spark/Hadoop 离线分析结果目录。
    analytics-result-path: /movie/result

management:
  endpoints:
    web:
      exposure:
        include: health,info
